// windows 1253
#define DEP_ "деп"
#define EDIP_ "едип"
#define EXTERNAL_ "енытеяийос"
#define TEACHING_ASSISTANT_ "богхос"
#define NAI_ "маи"
#define OXI_ "ови"
#define THEORY_ "хеыяиа"
#define LABORATORY_ "еяцастгяио"
#define TUTORING_ "жяомтистгяио"
#define MONDAY_ "деутеяа"
#define TUESDAY_ "тяитг"
#define WEDNESDAY_ "тетаятг"
#define THURSDAY_ "пелптг"
#define FRIDAY_ "паяасйеуг"
#define CREDITS_ "дидайтийес ломадес"
#define WORKLOAD_ "жоятос еяцасиас"
