// UTF-8
#define DEP_ "ΔΕΠ"
#define EDIP_ "ΕΔΙΠ"
#define EXTERNAL_ "ΕΞΩΤΕΡΙΚΟΣ"
#define TEACHING_ASSISTANT_ "ΒΟΗΘΟΣ"
#define NAI_ "ΝΑΙ"
#define OXI_ "ΟΧΙ"
#define THEORY_ "ΘΕΩΡΙΑ"
#define LABORATORY_ "ΕΡΓΑΣΤΗΡΙΟ"
#define TUTORING_ "ΦΡΟΝΤΙΣΤΗΡΙΟ"
#define MONDAY_ "ΔΕΥΤΕΡΑ"
#define TUESDAY_ "ΤΡΙΤΗ"
#define WEDNESDAY_ "ΤΕΤΑΡΤΗ"
#define THURSDAY_ "ΠΕΜΠΤΗ"
#define FRIDAY_ "ΠΑΡΑΣΚΕΥΗ"
#define CREDITS_ "ΔΙΔΑΚΤΙΚΕΣ ΜΟΝΑΔΕΣ"
#define WORKLOAD_ "ΦΟΡΤΟΣ ΕΡΓΑΣΙΑΣ"
